Improved difficulty messages, network hashrate computation
koinos/koinos-block-producer pull request #55
Opened 2021-06-29 17:49 UTC by theoreticalbts

Closes #54.

2021-06-29 18:06 UTC, sgerbino requested changes

2021-06-29 18:06 UTC, sgerbino commented on libraries/block_production/pow_producer.cpp
> +#define TARGET_BLOCK_INTERVAL_MS 10000
This should be using `std::chrono` similar to `hashrate::update_interval`.  We also don't make assumptions about the PoW contract (like the target being a 10s block interval) and I'm not sure we should break that...

2021-06-29 22:36 UTC, theoreticalbts commented
> We also don't make assumptions about the PoW contract (like the target being a 10s block interval) and I'm not sure we should break that...

I agree that in theory it would be better if we asked the smart contract what its target block interval is, but in practice this getter isn't implemented in the smart contract and I wanted to make it work with the smart contract we've got.

I wasn't sure this would be possible without changing the smart contract, but I was able to figure out a way to calculate an implied network hashrate from the metadata object returned by the API.  So I've added this improvement, it no longer assumes any particular target interval *and* it works with the PoW smart contract as-is!

> This should be using std::chrono similar to hashrate::update_interval

We get input in the form of numbers of `timestamp_type` directly from inside the VM, and we give output in the form of a rate with an implicit dimension of inverse seconds.  Since neither the input nor output interfaces we're talking to use `chrono`, using `chrono` would only be changing the internals of the computation this patch is doing.

2021-06-30 01:07 UTC, sgerbino approved these changes

2021-06-30 01:29 UTC, merged